config/routes.rb
Rails.application.routes.draw do

  get 'coffee_blends/index'

  get 'coffee_blends/coffee'

  get 'home', to: 'pages#home', as: 'home'

  get 'about_us', to: 'pages#about', as: 'about'

  get 'lizard/:number', to: 'pages#lizards', as:'lizards'

  get 'coffee_blends', to: 'coffee_blends#index', as: 'coffee_blends'
  
    get 'coffee_blends/:id', to: 'coffee_blends#coffee', as:'coffee_blend'
  
  root to: 'pages#home', as: 'root'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coffee_blend.rb
class CoffeeBlend < ApplicationRecord
    validates :blend_name, presence: true
    validates :blend_name, length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coffee_blends_controller.rb
class CoffeeBlendsController < ApplicationController
  def index
    @coffee_blends = CoffeeBlend.all
  end

  def coffee
    @coffee = CoffeeBlend.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end

  def lizards
    @lizard =  Emoji.find_by_alias("lizard").raw
    @lizard_num = params[:number].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffee_blends_helper.rb
module CoffeeBlendsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/coffee_blends/_coffee_blend.html.erb
<div class="coffee_blend">
    <p>
        <strong>Coffee Blend: </strong> <%= coffee_blend.blend_name %>
    </p>
</dvi>

app/views/coffee_blends/coffee.html.erb
<%= render partial: 'coffee_blend', object: @coffee %>

app/views/coffee_blends/index.html.erb
<%= render partial: 'coffee_blend', collection: @coffee_blends %>

app/views/common/_menu.html.erb
<header>
    <nav>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
      </ul>
    </nav> 
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render partial: 'common/menu'%>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
    <h2>"Lorem ipsum Excepteur sint occaecat cupidatat non proident, 
    sunt in culpa qui officia deserunt mollit anim id est laborum." <h2>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Home</h1>
        <li><%= link_to '12 Lizards', lizards_path(12) %></li>
        <li><%= link_to '444 Lizards', lizards_path(444) %></li>
        <li><%= link_to '9672 Lizards', lizards_path(9672) %></li>

        <h2>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." <h2>

app/views/pages/lizards.html.erb
<% @lizard_num.times do |i| %>
  <h1><%=@lizard%></h1>
<% end %>